services:
  - type: web
    name: intasend-payment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn intasend_payment.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: intasend_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: intasend_payment.settings
    buildFilter:
      paths:
        - requirements.txt
        - "**.py"
        - templates/**
        - static/**

databases:
  - name: intasend_db
    databaseName: intasend
    user: intasend 