services:
  - type: web
    name: intasend-payment
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn intasend_payment.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: sqlite:///db/db.sqlite3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: intasend_payment.settings
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/db
      sizeGB: 1 